name: Godot Build
on: [push]

jobs:
  export-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Game
        uses: firebelley/godot-export@v6.0.0
        with:
          # نترك الأداة تحمل الإصدار الافتراضي بدون روابط يدوية
          # ونحدد فقط مسار المشروع
          relative_project_path: ./
          archive_output: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-build
          path: ./.github/build/
